# Generated by Django 5.2.17 on 2026-09-01 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Start time of the working window (e.g., 09:00).')),
                ('end_time', models.TimeField(help_text='End time of the working window (e.g., 14:00).')),
            ],
            options={
                'verbose_name': 'Availability Rule',
                'verbose_name_plural': 'Availability Rules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='blockeddate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='user',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='buffer_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Required break/buffer time after the meeting in minutes.'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='allowed_channels',
            field=models.JSONField(default=list, help_text="List of allowed channels, e.g., ['google_meet', 'phone']"),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration of the meeting in minutes.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
