# Generated by Django 5.2.17 on 2026-09-07 22:27

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='answers',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Client responses to custom questions configured for this event type.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='booking_questions',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Configuration of custom form fields to collect during booking.'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='included_features',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text="List of included points (e.g., 'Presentation', 'Feasibility Assessment')."),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_custom_duration_allowed',
            field=models.BooleanField(default=False, help_text='If True, clients can select custom duration multiples.'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service price (0.00 for free services).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='allowed_channels',
            field=django_jsonform.models.fields.JSONField(default=list, help_text='Select accepted communication channels.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='buffer_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Required break time after the meeting in minutes.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='color',
            field=models.CharField(default='#38bdf8', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Standard duration of the meeting in minutes.'),
        ),
    ]
