# Generated by Django 5.2.17 on 2026-09-15 13:42

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_answers_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='answers',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Client responses to custom questions.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='booking_questions',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Configuration of custom form fields.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='included_features',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='List of included points.'),
        ),
    ]
